["setup.cfg".flake8]
format = "wemake"
show-source = true

# Plugins:
max-line-length = 120
max-complexity = 6

# darglint:
docstring-style = "google"

# Violations:
ignore = "D100,D101,D102,D103,D104,D107,WPS305,WPS306,H601"
per-file-ignores = "tests/**.py:WPS218,WPS432,WPS442,S101,src/**/version.py:WPS410"
inline-quotes = "double"

[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.per-file-ignores"]
